server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import:
      - nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}?server-addr=${spring.cloud.nacos.config.server-addr}
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.64.2:8848
      config:
        server-addr: 192.168.64.2:8848
        file-extension: yaml
#????
    gateway:
      routes:
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**