server:
  port: 8000

spring:
  application:
    name: gateway-service
  config:
    import:
      - nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}?server-addr=${spring.cloud.nacos.config.server-addr}
  autoconfigure:
    exclude:
      - com.emily.mall.common.config.WebMvcConfig
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.64.2:8848
      config:
        server-addr: 192.168.64.2:8848
        file-extension: yaml

#网关
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: cart-service
          uri: lb://cart-service

          #路由断言，判断某个请求的路由是否符合规则
          predicates:
            - Path=/cart/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**

jwt:
  secret: emily-is-gonna-be-rich-888888888888888888
  expiration: 86400000
